Repository igniphp/framework, pull requests merged in 2018-06, with the labels that each got.

#9 Expose settings property on server object
  src/Http/Router.php
  src/Http/Server.php
Labels: enhancement

#20 Exception handling docs + tests.
  docs/README.md
  src/Http/Exception/GenericHttpException.php
  src/Http/Exception/HttpException.php
  src/Http/Exception/HttpExceptionInterface.php
  src/Http/Exception/MethodNotAllowedException.php
  src/Http/Exception/NotFoundException.php
  src/Http/Exception/RouterException.php
  src/Http/Middleware/NotFoundMiddleware.php
  src/Http/Router.php
  tests/Fixtures/CustomHttpException.php
  tests/Functional/Http/Middleware/ErrorMiddlewareTest.php
  tests/Functional/Http/Middleware/NotFoundMiddlewareTest.php
  tests/Functional/Http/RouterTest.php
Labels: documentation, enhancement

#21 Issue #11 - Containers explained
  docs/README.md
  src/Application/Application.php
  src/Application/Container.php
  src/Http/Application.php
Labels: documentation, enhancement

#16 Issue #10 - Router and Route interface.
  examples/Controllers/GoodbyeController.php
  examples/Modules/SimpleModule.php
  examples/build_in_server_daemonized_example.php
  examples/modular_application_example.php
  src/Http/Application.php
  src/Http/Controller.php
  src/Http/Controller/ControllerAggregate.php
  src/Http/Exception/RouterException.php
  src/Http/Route.php
  src/Http/Router.php
  src/Http/Router/Route.php
  src/Http/Router/Router.php
  tests/Fixtures/HttpController.php
  tests/Functional/Http/Controller/ControllerAggregateTest.php
  tests/Functional/Http/RouteTest.php
  tests/Functional/Http/RouterTest.php
Labels: bc-break, enhancement
